// ============================================================================
// datos-seed.js
// ----------------------------------------------------------------------------
// Valores iniciales de cada catálogo de la sección "Datos", transcritos de
// las hojas de referencia enviadas (pestaña "DATOS" de Control General -
// Casos 2026). Estos valores se guardan en Firestore SOLO la primera vez
// que un usuario abre "Datos" y ese catálogo todavía no existe — a partir
// de ahí el usuario controla la lista por completo (agregar/eliminar) desde
// la propia pantalla de Datos, sin que este archivo la vuelva a sobreescribir.
// ============================================================================

export const SEED_DOCTORES = [
"ABNER GARCÍA","ABRAHAM ESPAÑA","ADRIANA BARRIOS","ALAN AYALA","ALBERTO SILVA","ALDO LOPEZ",
"ALEJANDRA ALVAREZ","ALEJANDRA CELADA","ALEJANDRA COJULUM","ALEJANDRA LOPEZ","ALEJANDRA MOSCOSO",
"ALEJANDRA RODAS","ALEJANDRO BRAVO","ALLISON PORTILLO","ALMA CONTRERAS","ALVARO AGUILAR",
"ALVARO BARRIENTOS","ÁLVARO GARCÍA","ALVARO VAN","AMPARO ELIZABETH LOPEZ","ANA AHUAT","ANA CHAJ",
"ANA DE LEON","ANA GARCIA","ANA LILY JUAREZ","ANA LUCIA AGUIRRE","ANA LUCIA BARRIOS",
"ANA LUCIA GARCIA","ANA LUCRECIA DE LEON","ANA LUISA CORADO","ANA MARIA JUAREZ","ANA RUTH QUINTANA",
"ANA UMUL","ANAITHE OROZCO","ANDREA DEL VALLE","ANDREA GONZALEZ","ANDREA GUANÉ","ANDREA ISABEL SAY",
"ANDREA MARTINEZ","ANDREA MORALES","ANDREA SAY","ANDY MAZARIEGOS","ANGEL POLANCO LOPEZ",
"ANNYANCY CASTAÑEDA","ANTONY OSCAR CARMEL","ARAMIS NAVAS","ASTRID CASTILLO","BEATRIZ ILLESCAS",
"BERNY LEONARDO","BERTHA DE LEÓN","BORIS ALEXIS ARGUETA MARTINEZ","BRENDA SAPON",
"BRIANDA ELIZABETH LÓPEZ","BRYANT COTI","BYRON PEREZ","CANDY DE LEÓN","CARLOS ALFONSO ALMENGOR",
"CARLOS ANTONIO ARANGO FLORES","CARLOS AVILA","CARLOS CARDONA","CARLOS DANIEL AQUINO",
"CARLOS ESTRADA","CARLOS JOSE BARRIOS HERNANDEZ","CARLOS PÉREZ","CARLOS RODAS","CARLOS SARAT",
"CARMEN DE LEON","CAROLINA CRUZ","CECILIA FLORES","CHRISTIAN ORDOÑEZ","CINDY MORALES",
"CINTIA MEJIA","CLAUDETH MARTINEZ","CLAUDIA CIFUENTES","CLAUDIA LÓPEZ","CLAUDIA MARIA TAY",
"CLAUDIA PAIZ MEDINA","CONRADO DUCAS","CRISTABEL SANTIZO","CRISTIAN JOSUE ROJAS","CRISTIAN LOPEZ",
"CYNTHIA BARAHONA","DALIA ARGUETA","DANIEL HUINAC","DANIA CRUZ","DANIEL MENDEZ","DAVID BARRENO",
"DENNYS ARDON","DÉNYS RUBÍ RAMÍREZ GÓMEZ","DIANA RECINOS","DIANNE AMARAL","DIEGO ALEJANDRO MORALES",
"DIEGO PEREZ","DONOVAN MORALES","DULCE BARREONDO","EDDY GALVAN","EDDY MAZARIEGOS",
"EDNA FABIOLA DIAZ DIAZ","EDNA LUCRECIA LOPÉZ","EDUARDO ESPINOZA","EDUARDO GALVEZ SAY",
"EDUARDO MERIDA","EDWAR SANTOS","EDWIN RISCAJCHE","EDY GALVAN","EDY URIAS","ELENA LOPEZ",
"ELISA BERNAL","ELISA GOMEZ","ELSA CASASOLA","ELVIN AMADO TALE","EMILIO GALLARDO",
"ESDRAS ABDIEL MORALES","ESDRAS MORALES","ESTEFANIA POLANCO","ESTUARDO RODAS","EVELIA",
"EVELYN CICLALY GONZALEZ","EVELYN CROCKER","EVELYN GÓMEZ","EVELYN MARROQUIN","EVELYN PELAEZ",
"FABIOLA DIAZ","FABIOLA LÓPEZ","FABIOLA NAVARRO","FÁTIMA PÉREZ","FERNANDA RUIZ",
"FERNANDO CASTAÑEDA","FERNANDO CASTILLO","FERNANDO ESCOBAR","FERNANDO MORALES",
"FERNANDO RONINESETH","FLOR DE MARIA WOLTERS","FLOR GOMEZ","FRANCISCO FERNANDEZ",
"FRANCISCO VALDEZ","FRANCISCO VILLATORO","FRANKLIN GARCÍA","GABRIELA BALTAZAR","GABRIELA GARCIA",
"GABRIELA OBIN","GABRIELA REYES","GALILEA VILLATORO","GERARDO DANIEL QUIJIVIX","GERARDO PINZÓN",
"GILMAR OROZCO","GLADYS HERNANDEZ","GLORIA MERIDA","GRETEL MALDONADO","GRUBER ANALY ALVARADO",
"GUADALUPE FONSECA","GUILLERMO GÁLVEZ","GUILLERMO GONZÁLEZ","GUILLERMO RAMIREZ","HECTOR CORDON",
"HÉCTOR GONZALEZ","HECTOR PINEDA","HEIDY FIGUEROA","HELEN PISQUIY","HERMAN MAX",
"HOMERO GORDILLO","HUBER GARCIA","INGRID COYOY","ISABEL ABARCA","ISABEL GUTIERREZ",
"IVAN CIFUENTES","IVAN GATICA","IVAN LIZAMA","IVETH GÁLVEZ RUIZ","IVONNE ESCOBAR",
"JAQUELIN ALVAREZ","JAQUELIN MORALES","JESSICA PÉREZ","JHOSE ELI LOPEZ","JOHANNA MARINE REYES",
"JOHASIS CASTILLO","JORGE ESPINOZA","JORGE HERMAN MAX","JORGE INTERIANO","JORGE MENDEZ",
"JORGE OLIVA","JORGE ROBERTO VALDES","JOSE ALEJANDRO DE LEON","JOSE ALFREDO COJTI",
"JOSE ARTURO LEMUS","JOSE FERNANDO CASTILLO","JOSE FERNANDO GARCIA","JOSE PABLO RACANCOJ",
"JOSUE VILLATORO","JUAN CARLOS BUCARO","JUAN CARLOS CARDONA","JUAN CASTRO","JUAN JOSÉ SOSA",
"JUAN MANUEL DIAZ","JUAN MANUEL SALAZAR","JUAN PABLO CHACÓN","JUAN PABLO GALINDO",
"JULIO ALEJANDRO WER","KAREN LOPEZ","KARINA TORRES","KARLA COBAR","KARLA CORZO",
"KARLA JISSEL ESTRADA RODAS","KARLA SIERRA","KATALYN RECINOS","KENNETH IXPEC","KEVIN PINTO",
"KEVIN RAMOS","KEVIN YOC","KIMBERLY NORIEGA","KLISMAN REYES","KRISTEL MENDEZ","LABORATORIO",
"LAURA ESTRADA","LAURA NAVICHOQUE","LAURA RUANO DE LEON","LENIN ROSALES","LEONEL OCHOA",
"LIDIA ANDRADE","LIGIA CASASOLA","LIMNI PEREZ","LORENA AVILA","LOURDES BARRENO",
"LOURDES COYOY","LOURDES HERRERA","LUCIA AGUIRRE","LUCIA MARTINEZ","LUCIA REYNA",
"LUIGI MANUEL ACEVEDO","LUIS FERNANDO RODAS GIRON","LUIS LANG","LUIS PAZ","LUIS TOLEDO",
"LUIS VALLE","LUIS VIDAL","LUISA LA GUARDIA","LUMY BARRIOS","LUZ MERIDA","MAISTER DE LEON",
"MANUEL ACEVEDO","MARCO ANTONIO JUAREZ PEREZ","MARIA ANDREA VALDÉS","MARIA DE LOS ANGELES AQUINO",
"MARIA FERNANDA MAZARIEGOS","MARIA ILLESCAS","MARIA JIMENA MARQUEZ","MARIA JOSE AQUINO LARA",
"MARIA JOSE JOACHIN","MARIA JOSE LIMA","MARIA JOSE MIRANDA","MARIA JOSE MONT",
"MARIA JOSE SANCHEZ","MARIA REBECA ROJAS","MARIA RENE ZAMORA","MARIA TERESA SANDOVAL",
"MARIANA FIGUEROA","MARIANA LAM WOC","MARIELA IXCARAGUA","MARIELA ZAMORA","MARIO GARCIA",
"MARIO GUILLEN","MARIO MARROQUIN","MARISOL CASASOLA","MARLEN GONZALEZ","MARLENI MAZARIEGOS",
"MARUTH RAMIREZ","MARVIN LEMUS","MEICY IXTABALAN","MELANY QUINTEROS","MELCY GONZALEZ",
"MELISA CHAVAJAY","MELISSA DESTARAC","MELISSA MORALES","MELVA CASASOLA","MELVIN RODAS",
"MELVIN SOLIS","MIRIAM ORTEGA JUAREZ","MOISES CATTAM","MONICA ESTRADA","MÓNICA LÓPEZ",
"MÓNICA MENDEZ","MONICA MONJES","MONICA OVALLE","MONTENEL","MYNOR COLON","NATALI QUIÑONEZ",
"NESTOR CASTRO","NOÉ MARTINEZ","NOHEMI ESCALANTE","OBDULIO MALDONADO","OLGA DE ZEA",
"OMAR RODAS","ORLANDO ESPAÑA","OSBERTO DE LEON","OSCAR ARDAVIN","OSCAR BARRERA","OTTO SAENZ",
"PABLO JUÁREZ","PABLO MARIZUYA","PABLO MEJICANOS","PAOLO BARRIOS","PATRICIA MALDONADO",
"PEDRO ORDOÑEZ","PEDRO TEBALAN","RAFAEL CAJAS","RAFAEL SANCHEZ","RAFAEL ZAPETA","RAMIRO DAVILA",
"RAQUEL GALVEZ","RAUL MURGA","RICARDO LOPEZ","RICARDO RUANO","RICARDO ZAVALA","ROBERTO REYNA",
"ROCIO ESTURBAN","ROCIO RIOS","ROCIO VERAS","RONALD FERNANDEZ PALOMO","RONALD MONTENEGRO",
"RONALD VELASQUEZ","RONY MACARIO","ROSALBA RUIZ","ROSALBA TZUL","ROSANGELICA CIFUENTES",
"ROSEMARY HERNÁNDEZ","ROSMERY SALANIC","ROSSANGELL QUIROA","ROSY DEL AGUILA","RUDY IXCARAGUA",
"RUDY VILLEDA","SALVADOR ALVARADO","SAMUEL ALVARADO","SAMUEL POROJ","SARA MELISSA AVILA",
"SAUL CALDERON","SEBASTIAN LACAYO","SEBASTIAN VALDEZ","SERGIO ALARCÓN","SERGIO CHUM",
"SERGIO MENENDEZ","SHIRLEY RIOS ARGUETA","SILVANA FLORES","SILVIA PACAJOI","SINDY GARCIA",
"SINDY GRAMAJO","SOFIA ESCOBAR","SOFIA QUIJIVIX","SUSETH MEJIA","TANIA BARREDA","TELMA IXQUIAC",
"VALERIA MARIA RODRIGUEZ MAZARIEGOS","VALERIA RODRIGUEZ MAZARIEGOS","VALESKA RECINOS",
"VALESKA VASQUEZ","VANESSA BALTAZAR","VANGLENDER FERNANDEZ GRAMAJO","VELVETH MENDEZ",
"VERÓNICA ÁVILA","VICTOR HUGO DE LEON","VICTORIA CALDERON","VICTORIA MADRID",
"VIRGINIA ESTURBAN","VIVIAN LORENZO","WALESKA MENDEZ","WALESKA RECINOS","WENDY MARTINEZ",
"WENDY RAMIREZ","WILSON TEPEU","XIMENA ARGUETA","XIOMARA ESCOBAR","YANIRA RISCAJCHE",
"YAQUELINE DE LEON","YESELIN BARRIOS","YESENIA GONZALEZ","YESSENIA GRAMAJO",
"YESSICA S. IXCARAGUA","YOANY PAZ","YOSSELYNE GUZMÁN","YURI CHAJ","YURI MARIA HERRERA",
"ZAIDA CHAVAJAY","ZEGREB ZEA","ZULLY CASTILLO"
];

export const SEED_ETAPAS = [
"ACRILADO","ALETAS","ANÁLOGO","BARRA","C. CEROMERO CORRECCIÓN","C. CEROMERO TERMINADA",
"C. E-MAX BIZCOCHO","C. E-MAX CORRECCION","C. E-MAX TERMINADA","C. METAL TERMINADA",
"CARILLA E-MAX BIZCOCHO","CMP BIZCOCHO","CMP CORRECCIÓN","CMP TERMINADA","CMPH/C BIZCOCHO",
"CMPH/C TERMINADA","CMPSI BIZCOCHO","CMPSI TERMINADO","COLADO DE UCLA","CORONA IMPRESA",
"CORRECCIÓN","DOMO","ENCERADO CORRECCIÓN","ENCERADO DIAGNÓSTICO","ENCERADO DIGITAL",
"ENVÍO DEPARTAMENTAL","FORMADENTINA","GUARDA","IMPRESIÓN MODELO DIGITAL","INC TERMINADA",
"INCRUSTACION DE E-MAX TERMINADO","INCRUSTACIÓN DIGITAL","MARYLAN BIZCOCHO","MARYLAN TERMINADO",
"METALES","MODELOS","PROVISIONAL DE PMMA","PROVISIONAL TERMINADO","REPETICION","ROUCH",
"UCLAS","VIDRIAR","ZIRCONIO BIZCOCHO","ZIRCONIO TERMINADO"
];

export const SEED_COSTOS = [
15,20,25,30,35,40,45,50,52,55,58,60,62,70,75,80,95,100,105,110,115,125,140,150,162.5,175,180,
185,192.5,200,210,225,235,250,260,275,290,300,325,330,343,350,375,380,385,400,412,450,500,530,
550,595,600,625,650,700,750,850,900,1000,1250,1950,3500,4000
];

export const SEED_DESTINOS = [
"ALTA VERAPAZ","ARTES Y OFICIOS","ASCEND","ASOCIACION PROBIENESTAR","ATITLÁN","BIODENTAL",
"BIODENTAL (PLAZA YAS)","BOLIVAR","CC MINI PLAZA","CEGMA","CENTRA SUR SEGMA",
"CENTRO COMERCIAL LA QUINTA","CENTRO DENTAL SANTA APOLONIA","CHIMALTENANGO","CHIQUIMULA","CIAM",
"CIUDAD NUEVA, ZONA 2","CLIDE (SAN LUCAS)","CLÍNICA BOCA","CLINICA FRESH","CLÍNICA IN DENT",
"CLÍNICA RELAX DENTAL ZONA 10","COLONIA EL ROSAL","CONFORTDENT","CUNOC XELA",
"DENTA (CHIQUIMULA)","DENTA (CHIQUIMULA)(PERSONAL)","DENTA (EL PROGRESO)","DENTA ZONA 11",
"DENTAL FRESH","DENTAL HOUSE Z16","DENTI TREE","DENTOK - KAMINAL JUYU 1 ZONA 7",
"DENTOK - ZONA 6 MIXCO","DISTRITO MIRAFLORES","EDIFICIO PLAZA TIVOLI","EDIFICIO RODRIGUEZ",
"EL TESORO","ENDODONCIA","ESCUINTLA","ESQUIPULAS","ETIZA","FAMILY DENTAL","GALERIAS DEL SUR",
"GEMINIS ZONA 10","HUEHUETENANGO","IGSS ZONA 5","IZABAL","JALAPA","JUSTO RB","KAMINAL JUYU",
"KAMINAL JUYU 2","KIRIOS","KONAMOR","LAS MARGARITAS","LOMAS DEL RODEO","LOS CEDROS","MAJADAS",
"MALACATAN","MARGARITAS TORRE 2","MAZATENANGO","MESOAMERICANA","MESOAMERICANA QUETZALTENANGO",
"MONSERRAT","MULTIDENT (CHIMALTENANGO)","MULTIDENT (SAN LUCAS)",
"MULTIDENT CHIMALTENANGO PLAZA REAL","MULTIDENT CHIMALTENANGO PRADERA","MULTIDENT SAN CRISTÓBAL",
"NUEVA SANTA ROSA","ODONTOSTETIC","ORTODENTAL","PACHALUM, QUICHE","PAJAPITA","PANAJACHEL",
"PERSONAL","PLAZUELA ESPAÑA","POAQUIL","PORTAL PETAPA","Q DENTAL","QUETZALTENANGO",
"RELAX DENTAL MAJADAS","RETALHULEU","RIE GENIAL ROOSEVELT","SALUCENTRO","SAN CRISTOBAL",
"SAN JOSE PINULA","SAN JUAN","SAN LUCAS","SAN MARCOS","SAN PEDRO","SAN PEDRO LA LAGUNA",
"SAN PEDRO SACATEPEQUEZ","SANARATE","SANTA CATARINA PINULA","SANTA MARÍA","SANTIAGO, ATITLAN",
"SC DENTAL","SIERVOS DE LA CARIDAD","SOCIAL DENT (SAN LUCAS)","SOLOLA","SUCHITEPEQUEZ",
"TIKAL FUTURA","UPANA","USAC","UTATLAN","VILLA DENTAL","VILLA LOBOS","ZACAPA","ZONA 1",
"ZONA 10","ZONA 11","ZONA 12","ZONA 13","ZONA 14","ZONA 14 (PERSONAL)","ZONA 15","ZONA 18",
"ZONA 19 LA FLORIDA","ZONA 3","ZONA 3 DE MIXCO","ZONA 5","ZONA 6","ZONA 7","ZONA 9",
"ZONA 9 TORRE AZUL","RIO DULCE"
];

export const SEED_STATUS = [
"CANCELADO","CORRECCION","MODELOS","PRUEBA","REPETICION"
];

export const SEED_CORRECCION = [
"AGREGAR ENCIA","AGREGAR PORCELANA","ANATOMÍA","COLOR","DR. PERFORA","MUY ALTAS",
"NO ADAPTA","NUEVOS CORTES","SE FRACTURO","SE QUEBRO PORCELANA","VOLVER A VIDRIAR"
];

/** Definición de cada catálogo: id de almacenamiento, etiqueta visible y semilla inicial. */
export const DATOS_CATALOGS = [
  { id: 'doctores',   label: 'Doctores',              seed: SEED_DOCTORES,   numeric: false },
  { id: 'etapas',      label: 'Etapas',                 seed: SEED_ETAPAS,     numeric: false },
  { id: 'costos',      label: 'Costos C/U',             seed: SEED_COSTOS,     numeric: true  },
  { id: 'destinos',    label: 'Destinos',               seed: SEED_DESTINOS,   numeric: false },
  { id: 'status',      label: 'Status',                 seed: SEED_STATUS,     numeric: false },
  { id: 'correccion',  label: 'Corrección / Repetición', seed: SEED_CORRECCION, numeric: false }
];

/** Unidades: lista fija de 1 a 32, tal como en las hojas de referencia. */
export const UNIDADES_1_32 = Array.from({ length: 32 }, (_, i) => i + 1);
